name: coralline_flutter
description: "A reactive state management framework for Flutter based on chain of reactivity and lazy computation pipeline."

repository: https://github.com/pioneerjkf/coralline
issue_tracker: https://github.com/pioneerjkf/coralline/issues
topics:
  - flutter
  - state-management
  - reactivity
  - widgets
  - ui

resolution: workspace

version: 0.1.1

environment:
  sdk: ^3.6.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  coralline: ^0.1.0

  coralline_extensions: ^0.1.0
  
  meta: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
