name: coralline
description: "A high-performance Dart reactive framework implementing Chain of Reactivity and Lazy-computation pipelines."

repository: https://github.com/pioneerjkf/coralline
issue_tracker: https://github.com/pioneerjkf/coralline/issues
topics:
  - state-management
  - reactivity
  - pipeline
  - reactive

resolution: workspace

version: 0.1.2

environment:
  sdk: ^3.6.0

dependencies:
  meta: ^1.18.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
