name: coralline_flutter_example
description: "An example app demonstrating coralline_flutter."
publish_to: none

resolution: workspace

environment:
  sdk: ^3.6.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  coralline_flutter: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
